apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenetinsight-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces"]
  verbs: ["get", "list", "watch"]
