{{- if .Values.rbac.create | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kubenetinsight.labels" . | nindent 4 }}
{{- end }}
